### ISSUE TITLE
Add SSR support

### ISSUE THREAD

**Issue by jonaspauleta** [ozziexsh/laravel-jetstream-react#15]
Would like to see Inertia SSR added.
I have tried to add it by myself but ran into some issues. #

**Comment by ozziexsh** [comment]
oh cool I didn't realize SSR was released for inertia, I will look into adding this in the coming days 😄

**Comment by jonaspauleta** [comment]
> oh cool I didn't realize SSR was released for inertia, I will look into adding this in the coming days 😄

Jetstream have also been updated to include SSR option 😁

**Comment by ozziexsh** [comment]
@jonaspauleta I've got it working in #16 if you want to try it out early, otherwise i will release it in a day or so when i can triple test everything

**Comment by jonaspauleta** [comment]
> @jonaspauleta I've got it working in #16 if you want to try it out early, otherwise i will release it in a day or so when i can triple test everything

I have tried it now.
Even without running 'node public/js/ssr.js' it works, idk if it is supposed to.

**Comment by ozziexsh** [comment]
yeah it will return the non-ssr version as a fallback if you don't have that running :)

**Comment by jonaspauleta** [comment]
> yeah it will return the non-ssr version as a fallback if you don't have that running :)

That's cool, but, how can I be sure that SSR is running fine in my machine?

**Comment by ozziexsh** [comment]
make sure you have both the node process running and the laravel app being served

1) there should be no errors in the node process window, it should just read 

> Starting SSR server on port 13714...
> Inertia SSR server started.

if you navigate around pages it would log errors here if there were any

2) visit a page directly and do your browsers "view source" function

if you have SSR enabled you will see the rendered html (these two screenshots are of the /register page)

![Screen Shot 2022-04-21 at 7 36 57 AM](https://user-images.githubusercontent.com/2093630/164327494-79b571b7-bdd6-433b-a645-4642c38beb99.png)
![Screen Shot 2022-04-21 at 7 37 58 AM](https://user-images.githubusercontent.com/2093630/164327503-c7a4ba20-d5f3-4aa3-8799-5e5aacdc6e89.png)

versus this screenshot below which does not have SSR enabled so it is only a singe div being rendered (which inertia then boots into on the client side)

![Screen Shot 2022-04-21 at 7 37 09 AM](https://user-images.githubusercontent.com/2093630/164327585-b5075499-c28b-4030-bd72-46f07a020451.png)

**Comment by jonaspauleta** [comment]
Alright, thanks for your time and the explanation.
And thanks for making SSR available <3
