### ISSUE TITLE
Typescript intellisense broken

### ISSUE THREAD

**Issue by bradymwilliams** [ozziexsh/laravel-jetstream-react#40]
Most everything here works great but something seems to be off config wise where in VSCode it can't detect/import via the normal `^ + Space` flow from installed packages.

**Comment by ozziexsh** [comment]
Just tested this out and it appears to work fine so going to close this. Feel free to reopen if it is still happening but please include a reproduction repo

![Screenshot 2023-12-12 at 1 10 35 pm](https://github.com/ozziexsh/laravel-jetstream-react/assets/2093630/95d23a0e-a63e-4142-8e6a-b342d2758ef8)
