### ISSUE TITLE
TS2786: RouteContext.Provider cannot be used as a JSX component.

### ISSUE THREAD

**Issue by FrozenGod** [ozziexsh/laravel-jetstream-react#43]
The migration to React seems to have worked well, but there's that typescript IDE error. Should I ignore or there's a fix?

<img width="1045" alt="image" src="https://github.com/ozziexsh/laravel-jetstream-react/assets/1233353/88651212-e80b-4fdb-8c20-a757a3ca3654">

The same error appears on the `<App ...` tag.

Thanks

**Comment by FrozenGod** [comment]
And the exact same warning appears on the `TextInput`. I assume it will appear on more components as well.
`TS2786: TextInput cannot be used as a JSX component.`

**Comment by ozziexsh** [comment]
hey, just tried this with a new project and there are no errors to be found

it sounds like your environment isn't quite set up right, make sure your node modules are installed and/or try reloading the typescript service in your editor

if that doesn't fix it please share a reproduction repo here and i'll reopen the issue

**Comment by FrozenGod** [comment]
Didn't help. I'm using PHPStorm 2023.3.1.
https://github.com/FrozenGod/laravel-jetstream-react_reproduction

**Comment by ozziexsh** [comment]
It works in vscode just fine. I checked it out in phpstorm and saw the error, not too sure why this fixes it without spending a ton of time but do this:

install at least v5 of typescript

```
 npm i -D "typescript@^5.3.2"
```

update the jsx property in `tsconfig.json`

```diff
- "jsx": "react",
+ "jsx": "react-jsx",
```

**Comment by FrozenGod** [comment]
It works, thanks!
